# Feature Noise

In [6]:
import sys
DIR_ROOT = '../../'
sys.path.append(DIR_ROOT)
from src.noise import *
import pandas as pd

# Seleciona o dataset
DATASET_NAME = 'imdb'
df = pd.read_csv(f'{DIR_ROOT}data/{DATASET_NAME}_train.csv')

# Copia os dados originais e separa
X_train = df.drop(columns=['target'])
y_train = df['target'].to_frame()

## 10% Feature Noise - Tabular

In [2]:
#Define the categorical columns
colunas_categoricas = []

colunas_numericas = X_train.columns.difference(colunas_categoricas).tolist()

X_train_noisy = data_noise_tabular(X_train, y_train, numerical_columns=colunas_numericas, categorical_columns=colunas_categoricas, p=0.1)

df_compare_data = X_train - X_train_noisy
df_compare_data = df_compare_data[(df_compare_data != 0).any(axis=1)]
df_compare_data

=== AUDIT: data_noise_tabular ===
p: 0.1, random_state: 42
Num numeric columns: 4 | picked per instance: 1
Num categorical columns: 0 | picked per instance: 0
Instances changed per class:
  - 2: 4
  - 0: 4
  - 1: 4

    sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
5            0.000000          0.000000          -0.229159          0.000000
16           0.000000         -0.200790           0.000000          0.000000
18           0.000000         -0.177264           0.000000          0.000000
21           0.000000          0.000000          -1.574660          0.000000
33           0.000000          0.000000           0.631215          0.000000
41           0.000000          0.000000           3.497315          0.000000
48           0.807148          0.000000           0.000000          0.000000
57           0.000000          0.000000           0.000000          0.100000
67           0.000000          0.000000           0.000000          0.244191
72           0.000000          0.000000           0.000000         -0.411030
82           0.000000          0.000000           0.000000          0.119322
87           0.000000          0.000000           1.529118          0.000000

## 10% Feature Noise - Images

In [4]:
X_train_noisy = data_noise_images(X_train, y_train, DATASET_NAME, p=0.1)

df_compare_data = X_train - X_train_noisy
df_compare_data = df_compare_data[(df_compare_data != 0).any(axis=1)]
df_compare_data

=== AUDIT: data_noise_images (salt & pepper) ===
Dataset: digits, p: 0.1, random_state: 42
Total columns (pixels): 64, noisy columns per instance: 7
Instances changed per class:
  - 8: 14
  - 9: 14
  - 2: 14
  - 0: 14
  - 7: 14
  - 5: 14
  - 3: 14
  - 4: 14
  - 6: 14
  - 1: 14
Salt/pepper ratio per instance: 50/50 (extra to 'salt' if odd)

,pixel_0_0,pixel_0_1,pixel_0_2,pixel_0_3,pixel_0_4,pixel_0_5,pixel_0_6,pixel_0_7,pixel_1_0,pixel_1_1,...,pixel_6_6,pixel_6_7,pixel_7_0,pixel_7_1,pixel_7_2,pixel_7_3,pixel_7_4,pixel_7_5,pixel_7_6,pixel_7_7
21,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-16.0,...,0.0,-16.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
24,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-16.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
45,0.0,0.0,0.0,0.0,-3.0,0.0,0.0,0.0,0.0,0.0,...,16.0,0.0,0.0,0.0,-15.0,0.0,0.0,0.0,0.0,0.0
61,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-12.0,0.0
79,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1304,-16.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,-1.0,0.0,0.0,0.0,0.0
1322,0.0,0.0,0.0,0.0,0.0,13.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1334,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,12.0,0.0
1337,0.0,0.0,0.0,0.0,0.0,0.0,-16.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1342,0.0,0.0,-7.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,7.0,0.0,0.0

## 10% Feature Noise - Text

In [7]:
X_train_noisy = data_noise_text(X_train, y_train, col_name='review', p=0.1)
df['review_noisy'] = X_train_noisy['review']
df_compara_data = df[df['review'] != df['review_noisy']]
df_compara_data[['review', 'review_noisy']]
df_compara_data

=== AUDIT: data_noise_text ===
p: 0.1, random_state: 42, removal_prob_per_word: 0.2
Instances changed per class:
  - positive: 1875
  - negative: 1875

,review,target,review_noisy
19,I think I watched a highly edited version beca...,negative,I I edited version because nearly as graphic a...
21,What bird is that ? A maltese falcon. The only...,negative,What bird that ? A maltese falcon. The only th...
36,4 out of 10.<br /><br />This film was neither ...,negative,4 out of 10.<br /><br />This film was neither ...
47,"The movie, although not faithful to the origin...",positive,"The movie, not faithful to the novels, succeed..."
53,SPOILERS<br /><br />A buddy of mine said NEXT ...,positive,SPOILERS<br /><br />A buddy of mine said was b...
...,...,...,...
37474,"A film, first and foremost, should be good sto...",positive,"A film, and foremost, should good storytelling..."
37476,Bled starts as young female artist Sai (Sarah ...,negative,Bled starts as artist Sai (Sarah meets a myste...
37479,Chaplin is a doughboy in his final film of 191...,positive,"Chaplin is a doughboy his final film 1918, dou..."
37484,I have seen this film 3 times. Mostly because ...,negative,I have seen this film 3 Mostly because thinkin...
37485,Here's my first David Mamet directed film. Fit...,positive,"Here's my first Mamet directed film. Fitting, ..."

## Saving the Results

In [ ]:
# Gera o novo df com a combinação dos ruídos e salva na pasta certa.
new_df = X_train_noisy.copy()
new_df['target'] = y_train

new_df.to_csv(f'{DIR_ROOT}data/noise/feature/{DATASET_NAME}_train.csv', index=False)

# Mantém os dados de teste intactos e copia para a pasta nova
df_test = pd.read_csv(f'{DIR_ROOT}data/{DATASET_NAME}_test.csv')
df_test.to_csv(f'{DIR_ROOT}data/noise/feature/{DATASET_NAME}_test.csv', index=False)